

provincial_colors = {
    'Punjab': 'red',
    'Sindh': 'blue',
    'Balochistan': 'yellow',
    'Khyber-Pakhtunkhwa': 'orange',
    'Azad Kashmir': 'green',
    'Federally Administered Tribal Ar': 'brown',
    'Gilgit-Baltistan': 'brown',
    'Islamabad': 'green'
}

copernicus_lulc_flags = {
    '0': 'no_data',
    '10': 'cropland_rainfed',
    '11': 'cropland_rainfed_herbaceous_cover',
    '12': 'cropland_rainfed_tree_or_shrub_cover',
    '20': 'cropland_irrigated',
    '30': 'mosaic_cropland',
    '40': 'mosaic_natural_vegetation',
    '50': 'tree_broadleaved_evergreen_closed_to_open',
    '60': 'tree_broadleaved_deciduous_closed_to_open',
    '61': 'tree_broadleaved_deciduous_closed',
    '62': 'tree_broadleaved_deciduous_open',
    '70': 'tree_needleleaved_evergreen_closed_to_open',
    '71': 'tree_needleleaved_evergreen_closed',
    '72': 'tree_needleleaved_evergreen_open',
    '80': 'tree_needleleaved_deciduous_closed_to_open',
    '81': 'tree_needleleaved_deciduous_closed',
    '90': 'tree_needleleaved_deciduous_open',
    '82': 'tree_mixed',
    '100': 'mosaic_tree_and_shrub',
    '110': 'mosaic_herbaceous',
    '120': 'shrubland',
    '121': 'shrubland_evergreen',
    '122': 'shrubland_deciduous',
    '130': 'grassland',
    '140': 'lichens_and_mosses',
    '150': 'sparse_vegetation',
    '151': 'sparse_tree',
    '152': 'sparse_shrub',
    '153': 'sparse_herbaceous',
    '160': 'tree_cover_flooded_fresh_or_brakish_water',
    '170': 'tree_cover_flooded_saline_water',
    '180': 'shrub_or_herbaceous_cover_flooded',
    '190': 'urban',
    '200': 'bare_areas',
    '201': 'bare_areas_consolidated',
    '202': 'bare_areas_unconsolidated',
    '210': 'water',
    '220': 'snow_and_ice'
}
